apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployments
spec:
  revisionHistoryLimit: 10
  replicas: 2
  strategy:
    type: RollingUpdate  
    rollingUpdate:
      maxUnavailable: 50%  
      maxSurge: 50%
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebappcontainer
          image: kmounika11/maven-web-application 
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc1
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
